language: ruby
sudo: false

cache: bundler

script: "bundle exec rake"

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 1.9.3
  - 2.1.9
  - 2.2.10
  - 2.3.7
  - 2.4.5
  - 2.5.3
  - 2.6.3

gemfile:
  - Gemfile
